on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - "lasagna"
          - "freelancer-rates"
          - "vehicle-purchase"
          - "custom-signs"
          - "secret-agent"
          - "magician-in-training"
          - "santas-helper"
          - "lasagna-master"
          - "pizza-slices"
          - "high-score-board"
          - "poetry-club"
          - "master-mixologist"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        working-directory: ${{ matrix.dir }}
        run: swift test
