on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    strategy:
      matrix:
        dir:
          - "lasagna"
          - "freelancer-rates"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        working-directory: ${{ matrix.dir }}
        run: swift test
